# Generated by Django 4.1.4 on 2022-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('species', models.CharField(max_length=250)),
                ('char_class', models.CharField(max_length=250)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
