# Generated by Django 4.1.4 on 2022-12-19 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('character_create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
