# Generated by Django 4.1.4 on 2022-12-20 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character_create', '0003_character_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
